# Generated by Django 3.0.4 on 2020-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(default='1', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='votings',
            field=models.IntegerField(default=0),
        ),
    ]
