# Generated by Django 3.0.4 on 2020-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20200309_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='votings',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings_amount',
            field=models.IntegerField(default=1),
        ),
    ]
