# Generated by Django 3.0.4 on 2020-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20200310_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings_amount',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping01',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping01_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping02',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping02_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping03',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping03_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping04',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping04_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping05',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping05_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping06',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping06_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping07',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping07_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping08',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping08_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping09',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping09_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping10',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping10_amount',
            field=models.IntegerField(default=0),
        ),
    ]
