# Generated by Django 3.0.4 on 2020-03-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20200310_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='topping01',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping01_amount',
            new_name='topping1_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping02',
            new_name='topping2',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping02_amount',
            new_name='topping2_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping03',
            new_name='topping3',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping03_amount',
            new_name='topping3_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping04',
            new_name='topping4',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping04_amount',
            new_name='topping4_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping05',
            new_name='topping5',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping05_amount',
            new_name='topping5_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping06',
            new_name='topping6',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping06_amount',
            new_name='topping6_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping07',
            new_name='topping7',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping07_amount',
            new_name='topping7_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping08',
            new_name='topping8',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping08_amount',
            new_name='topping8_amount',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping09',
            new_name='topping9',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping09_amount',
            new_name='topping9_amount',
        ),
    ]
