# Generated by Django 3.0.4 on 2020-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20200310_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
