# Generated by Django 3.0.4 on 2020-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_auto_20200310_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
