# Generated by Django 3.0.4 on 2020-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0009_auto_20200310_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='nr_of_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='total_toppings_amount',
            field=models.IntegerField(default=0),
        ),
    ]
