# Generated by Django 3.0.4 on 2020-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0010_auto_20200311_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
